config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  get '/products', :to => 'products#index'
  get '/products_list', :to => 'products#products'
  post '/create_product', :to => 'products#create_products'
  mount ShopifyApp::Engine, at: '/'
  get 'home/index' => 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorageWithScopes

  def api_version
    ShopifyApp.configuration.api_version
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop
  include ShopifyApp::ShopAccessScopesVerification

  def index
    if ShopifyAPI::Context.embedded? && (!params[:embedded].present? || params[:embedded] != "1")
      redirect_to(ShopifyAPI::Auth.embedded_app_url(params[:host]) + request.path, allow_other_host: true)
    else
      @shops = Shop.all
      @shop_origin = current_shopify_domain
      @host = params[:host]
      @count = Shop.count

    end
  end


  # def get_result
  #   flash = "SQLite Database"
  #   return flash
  # end
  # helper_method :get_result

end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < AuthenticatedController

  skip_before_action :verify_authenticity_token

  def index
    # product = ShopifyAPI::Product.new
    # product.product_type = "Accessories"
    # product.title = "Watches For Men"
    # product.body_html  = "<strong>Good Watches and Suitable for Mens</strong>"
    # product.vendor = "MG Test Store 2"
    # product.price = "10.0"
    # # product.variants = []
    # product.save


    @products = ShopifyAPI::Product.all
    @ss = ShopifyAPI::Product.count
    # @ss1 = ShopifyAPI::Shop.current

    render(json: { products: @products, ss: @ss, ss1: @ss1 })
  end

  def products
    #  pyload = JSON.parse(string)
    response = RestClient.get("https://mg-test-store-1.myshopify.com/admin/api/2020-10/products.json",
                              { 'X-Shopify-Access-Token': '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' })

    res = JSON.parse(response.body)
    @products_list = res['products']
    render json: {products_list: @products_list}
  end

  def create_products
    url = "https://mg-test-store-2.myshopify.com/admin/api/2022-10/products.json"
    response = RestClient.post(url , {
    "product": {
        "title": "Shirts MG Test",
        "body_html": "\u003cstrong\u003eGood Yahooo!\u003c/strong\u003e",
        "vendor": "MG Test Store 1",
        "product_type": "Accessories",
        "variants":[
            {
                "option1":"Small",
                "title":"Small",
                "price":10,
                "weight":10
            },
            {
                "option1":"Large",
                "title":"Large",
                "price":20
            }
        ]
    }
    },
                               { 'X-Shopify-Access-Token': "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" }
    )

    res = JSON.parse(response.body)
    render json: {products_list: res}
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_store_helper.rb
module LoginStoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link
    rel="stylesheet"
    href="https://unpkg.com/@shopify/polaris@4.25.0/styles.min.css"
    />
  <script src="https://unpkg.com/@shopify/app-bridge@2"></script>

</head>

<body>

<h5 style="font-size: medium"> Currently in <b><%= @shop_origin %></b> Shop </h5>
<br>


<!--var link = `<a target="_top" href="https://<%#= @shop_origin %>/admin/products/${product.id}">`-->
<% if @count > 1 %>

  <%= @ss %>
  <div class="row" style="font-size: medium">
    <div class="col-md-4">
      <label class="form-label">Select Shop To Transfer Product</label>
    </div>
    <div class="col-md-7">
      <select id="shops" class="form-select" style="font-size: small">
        <% for shop in @shops %>
          <% if shop.shopify_domain != @shop_origin %>
            <option value="<%= shop.shopify_domain %>"><%= shop.shopify_domain %></option>
          <% end %>
        <% end %>
      </select>
    </div>
  </div>
  <br><br>

  <h5 style="font-size: medium">Products of <%= @shop_origin %></h5>
  <div id="products" style="font-size: medium"><br>Loading...</div>

<% else %>
  <p>Install One more Store to this App</p>
<% end %>

<br><br>
<hr>
<script>

    var data_products = [];

    let access_token = [];
    let shops = [];

    <% for shop in @shops %>
    shops.push('<%= shop.shopify_domain %>');
    access_token.push('<%= shop.shopify_token %>');
    <% end %>
    console.log(shops);
    console.log(access_token);

    async function displayProducts() {

        var fetchProducts = function () {
            var headers = new Headers({"Authorization": "Bearer " + window.sessionToken});

            return fetch("/products", {headers})
                .then(response => response.json())
                .then(data => {
                    let products = data.products;
                    data_products = products;
                    if (products === undefined || products.length == 0) {
                        document.getElementById("products").innerHTML = "<br>No products to display.";
                    } else {

                        var list = "";

                        products.forEach((product) => {
                            list += `<li style='margin: 15px;' id='${product.created_at}'>` + product.title + ` <button class='btn btn-outline-primary' style='font-size: medium'>Transfer Product</button>  </li>`;
                        });


                        console.log(data.ss1);

                        document.getElementById("products").innerHTML = "<ul style='font-size: medium' id='products'>" + list + "</ul>";
                    }
                });
        }();
    }

    document.addEventListener("DOMContentLoaded", displayProducts);


    $(document).ready(function () {

        let data = '';
        let called = false;
        $('.btn').click(function () {
            called = true;
        });

        async function postData(url = '', data = {}) {
            // Default options are marked with *
            const response = await fetch(url, {
                method: 'POST', // *GET, POST, PUT, DELETE, etc.
                mode: 'cors', // no-cors, *cors, same-origin
                cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
                credentials: 'same-origin', // include, *same-origin, omit
                headers: {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*',
                    'Access-Control-Allow-Methods': 'POST',
                    'Access-Control-Allow-Headers': 'Content-Type, Authorization'
                    // 'Content-Type': 'application/x-www-form-urlencoded',
                },
                redirect: 'follow', // manual, *follow, error
                referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
                body: JSON.stringify(data) // body data type must match "Content-Type" header
            });
            return response.json(); // parses JSON response into native JavaScript objects
        }

        $("#products").on('click', '.btn', function () {

            var id = $(this).closest('li').attr('id');
            var selected = $('#shops').val();
            for (let x in data_products) {
                if (data_products[x].created_at === id) {
                    let dd = data_products[x];
                    console.log(dd);
                    let variants = [];
                    let xx = ''
                    for (let x in dd.variants) {
                        xx = `{"option1":"${dd.variants[x].options1}","price":"${dd.variants[x].price}","weight":${dd.variants[x].weight}}`;
                        variants.push(JSON.parse(xx));
                    }
                    let op = [];
                    xx = ''
                    for (let x in dd.options) {
                        xx = `{"name":"${dd.options[x].name}"}`;
                        op.push(JSON.parse(xx));
                    }

                    let index
                    for (let x in shops) {
                        if (selected === shops[x]) {
                            index = x;
                        }
                    }
                    let token = '';
                    token = access_token[index];

                    $.ajax({
                        type: 'POST',
                        url: '/create_product',
                        success:function () {
                            alert("Product Created in Store 2");
                        }
                    });


                }
            }


        });


        $('#call').click(function () {

        });
    });


</script>
</body>
</html>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="utf-8">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Shopify App', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Add New App', home_index_path, class:'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <br>
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% elsif ShopifyApp.use_importmap? %>
      <%= javascript_importmap_tags %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://unpkg.com/@shopify/app-bridge@2"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: @shop_origin || (@current_shopify_session.shop if @current_shopify_session),
      host: @host,
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>